apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fiapeats-api-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /fiapeats
            pathType: Prefix
            backend:
              service:
                name: fiapeats-api-service
                port:
                  number: 80
